name: ansible-lint
on:
  pull_request:
    branches: ["master", "main"]
  workflow_dispatch:
jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install Ansible and ansible-lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint
      - name: Run Ansible Lint
        run: |
          ansible-lint
